apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: rhtap-test
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/alroy-tenant/rhtap-test/rhtap-test@sha256:b04a2159a4a4eac8443bfd4b97587252769094a71a73744e25041917d2cc8a2a
        name: my-java-springboot
        resources: {}
status: {}
